# Generated by Django 4.1 on 2022-08-12 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_reapeat_tag_task_repeat_task_tag"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Reapeat",
            new_name="Repeat",
        ),
    ]
