# Generated by Django 4.1 on 2022-08-14 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_rename_reapeat_repeat"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="due_date",
            field=models.DateField(default=datetime.date.today, verbose_name="Date"),
        ),
    ]
