# Generated by Django 4.1 on 2022-08-14 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_task_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="due_time",
            field=models.TimeField(default=datetime.time, verbose_name="Time"),
        ),
    ]
