# Generated by Django 4.1 on 2022-08-15 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_task_due_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="due_date",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="due_time",
            new_name="time",
        ),
    ]
