# Generated by Django 4.1 on 2022-08-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_rename_due_date_task_date_rename_due_time_task_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(default="task details", max_length=500),
        ),
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(default="Task name", max_length=200),
        ),
    ]
