# Generated by Django 4.1 on 2022-08-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_alter_task_description_alter_task_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="priority",
            name="name",
            field=models.CharField(
                choices=[
                    ("LP", "low priority"),
                    ("NM", "Normal"),
                    ("HP", "high priority"),
                ],
                default="NM",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="repeat",
            name="name",
            field=models.CharField(
                choices=[
                    ("RO", "Repeat Once"),
                    ("RD", "Repeat Daily"),
                    ("RW", "Repeat Weekly"),
                    ("RM", "Repeat Monthly"),
                ],
                default="RO",
                max_length=20,
            ),
        ),
    ]
