# Generated by Django 4.1 on 2022-08-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_alter_priority_name_alter_repeat_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="priority",
            name="name",
            field=models.CharField(
                choices=[
                    ("low priority", "low priority"),
                    ("Normal", "Normal"),
                    ("high priority", "high priority"),
                ],
                default="Normal",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="repeat",
            name="name",
            field=models.CharField(
                choices=[
                    ("Repeat Once", "Repeat Once"),
                    ("Repeat Daily", "Repeat Daily"),
                    ("Repeat Weekly", "Repeat Weekly"),
                    ("Repeat Monthly", "Repeat Monthly"),
                ],
                default="Repeat Once",
                max_length=20,
            ),
        ),
    ]
